# Generated by Django 4.1.6 on 2023-10-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='student name')),
                ('rank', models.CharField(max_length=50, verbose_name='student class')),
            ],
        ),
    ]
